from __future__ import annotations

import json
from dataclasses import dataclass, replace
from pathlib import Path

from lab3.common import Lab3Error, require_tool, run_cmd, monitored_block, timed_block
from lab3.reconstruction.base import ReconstructionContext, Reconstructor, ViewerTarget
from lab3.reconstruction.nerfstudio import (
    evaluate_nerfstudio,
    scheduled_train_command,
    train_monitor_command,
    validate_save_iterations,
)
from lab3.training_artifacts import export_training_scalar_artifacts


@dataclass(frozen=True)
class NeRFConfig:
    process_bin: str = "ns-process-data"
    train_bin: str = "ns-train"
    method: str = "nerfacto"
    max_num_iterations: int | None = 30000
    save_iterations: tuple[int, ...] = (2000, 5000, 10000, 20000, 30000)
    train_num_rays_per_batch: int | None = None
    # Number of 2x image-pyramid levels generated by ns-process-data.
    # Prepared inputs already have the configured training resolution, so zero
    # avoids redundant image copies by default.
    num_downscales: int = 0
    skip_process_data: bool = False
    # Shared COLMAP ``sparse/0`` dir. When set, ns-process-data reuses these
    # poses (``--skip-colmap --colmap-model-path``) instead of re-running COLMAP.
    colmap_model: Path | None = None


def config_from_dict(values: dict) -> NeRFConfig:
    return NeRFConfig(
        process_bin=str(values.get("process_bin", "ns-process-data")),
        train_bin=str(values.get("train_bin", "ns-train")),
        method=str(values.get("method", "nerfacto")),
        max_num_iterations=_optional_int(values.get("max_num_iterations", 30000)),
        save_iterations=tuple(int(step) for step in values.get("save_iterations", (2000, 5000, 10000, 20000, 30000))),
        train_num_rays_per_batch=_optional_int(values.get("train_num_rays_per_batch")),
        num_downscales=int(values.get("num_downscales", 0)),
        skip_process_data=bool(values.get("skip_process_data", False)),
        colmap_model=(
            None if values.get("colmap_model") in (None, "")
            else Path(str(values["colmap_model"]))
        ),
    )


def add_cli_arguments(parser) -> None:
    parser.add_argument("--nerf-iterations", type=int, help="nerfstudio training iterations")
    parser.add_argument("--nerf-save-iterations", nargs="+", type=int, help="explicit NeRF checkpoint iterations")
    parser.add_argument(
        "--nerf-train-rays-per-batch",
        type=int,
        help="override nerfstudio train_num_rays_per_batch",
    )


def cli_overrides(arguments) -> dict:
    return {
        key: value for key, value in {
            "max_num_iterations": arguments.nerf_iterations,
            "save_iterations": arguments.nerf_save_iterations,
            "train_num_rays_per_batch": arguments.nerf_train_rays_per_batch,
        }.items() if value is not None
    }


@dataclass(frozen=True)
class NeRFReconstructor(Reconstructor):
    config: NeRFConfig
    name: str = "nerf"
    consumes_shared_poses: bool = True

    def run(self, context: ReconstructionContext) -> None:
        processed_dir = (context.output_dir / "processed").resolve()
        train_dir = (context.output_dir / "train").resolve()
        images_dir = context.images_dir.resolve()
        colmap_model = self.config.colmap_model.resolve() if self.config.colmap_model is not None else None
        logs = context.run_dir / "logs" if context.run_dir else None
        if not context.dry_run:
            require_tool(self.config.process_bin)
            require_tool(self.config.train_bin)
            context.output_dir.mkdir(parents=True, exist_ok=True)

        if not self.config.skip_process_data:
            if self.config.num_downscales < 0:
                raise Lab3Error("NeRF num_downscales must be non-negative")
            cmd = [
                self.config.process_bin,
                "images",
                "--data",
                str(images_dir),
                "--output-dir",
                str(processed_dir),
                "--num-downscales",
                str(self.config.num_downscales),
            ]
            if colmap_model is not None:
                cmd.extend(
                    ["--skip-colmap", "--colmap-model-path", str(colmap_model)]
                )
            with timed_block("nerf_process_data", context.timings):
                run_cmd(
                    cmd,
                    dry_run=context.dry_run,
                    log_path=logs / "nerf_process_data.log" if logs else None,
                )

        transforms_path = processed_dir / "transforms.json"
        if context.dry_run:
            print(f"$ inject canonical split into {transforms_path}")
        else:
            split_counts = apply_nerfstudio_split(
                transforms_path,
                context.split.train,
                context.split.test,
                source_images_dir=images_dir,
            )
            print(
                "Nerfstudio canonical split: "
                f"{split_counts['train']} train / {split_counts['test']} test registered poses "
                f"({split_counts['dropped_train']} train / "
                f"{split_counts['dropped_test']} test dropped by COLMAP)"
            )

        train_cmd = [
            self.config.train_bin,
            self.config.method,
            "--data",
            str(processed_dir),
            "--output-dir",
            str(train_dir),
            "--vis",
            "tensorboard",
        ]
        if self.config.max_num_iterations is not None:
            train_cmd.extend(["--max-num-iterations", str(self.config.max_num_iterations)])
        if self.config.train_num_rays_per_batch is not None:
            if self.config.train_num_rays_per_batch <= 0:
                raise Lab3Error("NeRF train_num_rays_per_batch must be positive")
            train_cmd.extend(
                [
                    "--pipeline.datamanager.train-num-rays-per-batch",
                    str(self.config.train_num_rays_per_batch),
                ]
            )
        save_iterations = validate_save_iterations(
            self.config.max_num_iterations, self.config.save_iterations
        )
        # Explicit report checkpoints must coexist; override Nerfstudio's
        # latest-only default rather than exposing a conflicting config knob.
        train_cmd.extend(["--save-only-latest-checkpoint", "False"])
        if save_iterations:
            train_cmd = scheduled_train_command(train_cmd, save_iterations)

        if logs is not None:
            wrapped_cmd = train_monitor_command(train_cmd, logs / "nerf_train.log")
            train_log_path: Path | None = None
        else:
            wrapped_cmd = train_cmd
            train_log_path = None

        with monitored_block("nerf_train", context.timings, context.peaks, enabled=not context.dry_run):
            run_cmd(
                wrapped_cmd,
                dry_run=context.dry_run,
                log_path=train_log_path,
            )
        if logs is not None and not context.dry_run:
            export_training_scalar_artifacts("nerf", train_dir, logs)

    def evaluate(self, context: ReconstructionContext, eval_config, eval_dir: Path):
        return evaluate_nerfstudio(
            self.name,
            context,
            eval_config,
            self.config,
            eval_dir,
            notes="transforms.json contains the repository's explicit train/val/test filenames",
        )

    def stage_geometry(self, context: ReconstructionContext) -> list[Path]:
        from lab3.geometry import stage_exported_geometry

        return stage_exported_geometry(context, self.name)

    def qualitative_render_dir(self, run_dir: Path) -> Path:
        return run_dir / "results" / self.name / "renders"

    def viewer_targets(self, run_dir: Path) -> list[ViewerTarget]:
        train_root = run_dir / "results" / self.name / "train"
        configs = sorted(train_root.rglob("config.yml")) if train_root.exists() else []
        return [
            ViewerTarget(self.name, "external", path, ("--load-config", str(path)))
            for path in configs[-1:]
        ]

    def with_shared_poses(self, shared_dir: Path) -> Reconstructor:
        return replace(self, config=replace(self.config, colmap_model=shared_dir / "sparse" / "0"))


def apply_nerfstudio_split(
    transforms_path: Path,
    train_names: tuple[str, ...],
    test_names: tuple[str, ...],
    source_images_dir: Path | None = None,
) -> dict[str, int]:
    """Inject the canonical split after Nerfstudio renaming and COLMAP filtering.

    ``ns-process-data images`` copies sorted inputs to ``frame_00001.*``, etc.
    Its transforms then contain only images for which COLMAP found poses.  Keep
    each surviving image in its original canonical partition and omit genuinely
    unregistered images from both partitions.
    """
    if not transforms_path.is_file():
        raise Lab3Error(f"nerfstudio transforms.json not found: {transforms_path}")
    metadata = json.loads(transforms_path.read_text(encoding="utf-8"))
    frames = metadata.get("frames", [])
    paths_by_processed_name = {
        Path(str(frame["file_path"])).name: str(frame["file_path"])
        for frame in frames
        if "file_path" in frame
    }

    if source_images_dir is None:
        processed_name_by_source = {name: name for name in paths_by_processed_name}
    else:
        source_images = sorted(
            path for path in source_images_dir.rglob("*")
            if path.is_file() and path.suffix.lower() in {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".cr2"}
        )
        processed_name_by_source = {
            path.name: f"frame_{index:05d}{path.suffix}"
            for index, path in enumerate(source_images, start=1)
        }

    def resolve(names: tuple[str, ...]) -> tuple[list[str], int]:
        unknown = [name for name in names if name not in processed_name_by_source]
        if unknown:
            raise Lab3Error(f"Canonical split references source images absent from the dataset: {unknown[:5]}")
        resolved = [
            paths_by_processed_name[processed_name_by_source[name]]
            for name in names
            if processed_name_by_source[name] in paths_by_processed_name
        ]
        return resolved, len(names) - len(resolved)

    train_paths, dropped_train = resolve(train_names)
    test_paths, dropped_test = resolve(test_names)
    if not train_paths:
        raise Lab3Error("COLMAP registered no images from the canonical training split")
    if not test_paths:
        raise Lab3Error("COLMAP registered no images from the canonical test split")
    metadata["train_filenames"] = train_paths
    metadata["val_filenames"] = test_paths
    metadata["test_filenames"] = test_paths
    transforms_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return {
        "train": len(train_paths),
        "test": len(test_paths),
        "dropped_train": dropped_train,
        "dropped_test": dropped_test,
    }


def _optional_int(value: object) -> int | None:
    return None if value in (None, "") else int(value)
